// <auto-generated />
using DemoEComBlazor.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoEComBlazor.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220721173722_ProductSeeding")]
    partial class ProductSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DemoEComBlazor.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "he Road Ahead is a book written by Bill Gates, co-founder and previous chairman and CEO of Microsoft software company, together with Microsoft executive Nathan Myhrvold and former Microsoft vice president and Pulitzer Prize winner Peter Rinearson.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/e/e2/The_Road_Ahead_%28Bill_Gates_book%29.jpg",
                            Price = 9.99m,
                            Title = "The Road Ahead (Gates book)"
                        },
                        new
                        {
                            Id = 2,
                            Description = "How to Avoid a Climate Disaster: The Solutions We Have and the Breakthroughs We Need is a 2021 book by Bill Gates. In it, Gates presents what he learned in over a decade of studying climate change and investing in innovations to address global warming and recommends strategies to tackle it.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/7/70/How_to_Avoid_a_Climate_Disaster_%28Bill_Gates%29.png",
                            Price = 9.99m,
                            Title = "How to Avoid a Climate Disaster"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Business @ the Speed of Thought[1] is a book written by Bill Gates and Collins Hemingway in 1999. It discusses how business and technology are integrated, and explains how digital infrastructures and information networks can help someone get an edge on the competition.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/3/3d/Business_%40_the_Speed_of_Thought_%28book_cover%29.jpg",
                            Price = 9.99m,
                            Title = "Business @ the Speed of Thought"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
